version: '3.9'
services:
  nginx:
    container_name: lineShaper-proxyServer
    image: nginx:1.19
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - 9001:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/home/index.html
      - ./router/src/favicon.ico:/home/favicon.ico
  editor:
    container_name: lineShaper-mapEditor
    build:
      context: ./editor/
      dockerfile: Dockerfile
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      TZ: "Europe/Bratislava"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  router:
    container_name: lineShaper-lineRouter
    build:
      context: ./router/
      dockerfile: Dockerfile
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      TZ: "Europe/Bratislava"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  api:
    container_name: lineShaper-api
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      TZ: "Europe/Bratislava"
      EDITOR_AUTH: $EDITOR_AUTH
      ROUTER_AUTH: $ROUTER_AUTH
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  postgis:
    container_name: lineShaper-db
    image: postgis/postgis
    volumes:
      - ./api/:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGPORT: ${DB_PORT}
      TZ: "Europe/Bratislava"
    deploy:
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD", "pg_isready", "--username=${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
