CREATE EXTENSION postgis CASCADE;
CREATE TABLE IF NOT EXISTS railMap (gid SERIAL PRIMARY KEY, geom GEOMETRY, conns INT[]);
CREATE TABLE IF NOT EXISTS roadMap (gid SERIAL PRIMARY KEY, geom GEOMETRY, conns INT[]);
CREATE TABLE IF NOT EXISTS tramMap (gid SERIAL PRIMARY KEY, geom GEOMETRY, conns INT[]);
